In [1]:
import numpy as np
#import tools

In [3]:
#verify if the order is the same as the training order. yes.
#get the training labels
#make empty matrix
#for each class
#    get the indices of the samples with class i
#    get corresponding entries in the prob_
#    for each class:
#        compute mean
#        fill in the corresponding entry of the matrix

In [31]:
num = 4
model_index = 19

In [32]:
y_train = np.load('./mnist/mnist-train_labels.npy')

#prob_save_dir='./50_sym_cf10/prob_'+str(num)+'/cifar10/noise_rate_0.0/'
prob_save_dir='./mnist/mnist_sym_80/'
A_save_dir = prob_save_dir + str(num) + '_prob.npy'
#np.save(A_save_dir, A)           
prob_ = np.load(A_save_dir)
print(prob_.shape)
num_classes = 10

best = prob_[model_index, :, :]

indices_list = {}
Q = np.empty((num_classes, num_classes))
for c in range(num_classes):
    indices_list[c] = [x for x in range(len(y_train)) if y_train[x] == c]
    temp = best[indices_list[c], :]
    #print(c, temp.shape)
    for j in range(num_classes):
        Q[c, j] = np.mean(temp[:, j])
        
import csv

record_file = prob_save_dir+'mnist_sym_80_avg_prior.csv'
#rc = {}
#rc['true T'] = True_T
#rc['initial T'] = T
#for ke in rc:
with open(record_file, 'a', newline='') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerow('trial')
    for roww in range(Q.shape[0]):
        writer.writerow(np.array(Q[roww, :]))
csvFile.close()

(20, 60000, 10)


In [6]:
print(np.around(Q, decimals=4))

[[0.2794 0.0625 0.0746 0.0768 0.0979 0.0685 0.0662 0.0678 0.1249 0.0813]
 [0.0619 0.3664 0.0525 0.0544 0.0682 0.0576 0.0644 0.0643 0.0862 0.124 ]
 [0.101  0.0516 0.256  0.096  0.1005 0.0939 0.1001 0.0718 0.0623 0.0667]
 [0.0724 0.0595 0.0841 0.2311 0.0835 0.1341 0.1163 0.0784 0.0671 0.0734]
 [0.0776 0.0539 0.0991 0.0831 0.2685 0.0879 0.1098 0.0964 0.0579 0.0657]
 [0.071  0.0597 0.0685 0.1379 0.0742 0.2897 0.0829 0.0875 0.0605 0.068 ]
 [0.0597 0.0502 0.0787 0.0721 0.0816 0.0639 0.4139 0.0559 0.0626 0.0612]
 [0.064  0.0607 0.0671 0.077  0.1009 0.0924 0.0745 0.3412 0.0599 0.0623]
 [0.0681 0.058  0.0516 0.0688 0.0677 0.0625 0.0622 0.068  0.4151 0.0778]
 [0.0669 0.0801 0.0554 0.0658 0.0634 0.0587 0.0628 0.0797 0.0744 0.3928]]
